import type { Dossier } from "@/lib/dossier-core";
export const pilotDossier: Dossier = {
    slug: "de-uitgang-is-vol", title: "De uitgang is vol", themes: ["Wonen", "Zorg", "Bestuur"],
    description: "Een onderzoeksopzet over passende woonruimte, uitstroom uit zorg en de gevolgen van wachten. De centrale vraag staat open; conclusies zijn nog niet vastgesteld.",
    question: "Of, waar en hoe belemmert het ontbreken van passende woonruimte de uitstroom uit zorg?",
    method: "We willen de route van een mogelijke vervolgplek tot de daadwerkelijke verhuizing reconstrueren. Ervaringen, besluiten en capaciteitsgegevens worden apart beoordeeld en pas daarna met elkaar verbonden.",
    boundaries: "Onderzoeksopzet, geen vastgesteld resultaat. Er zijn nog geen gecontroleerde bronverwijzingen of bevindingen aan dit dossier toegevoegd. Het is daarom niet opgenomen in de sitemap.",
    status: "Onderzoeksopzet · bronnen nog aan te vullen", indexable: false, articles: [],
    chapters: [
        { id: "onderzoeksvraag", title: "Welke uitstroom onderzoeken we?", paragraphs: ["Het onderzoek begint bij een afbakening: welke voorziening, welke groep en welke periode worden onderzocht? Uitstroom uit een instelling, tijdelijke opvang en vervolgzorg zijn niet vanzelf hetzelfde. Deze routes moeten eerst afzonderlijk worden beschreven.", "De vraag is niet vooraf of woningtekort de verklaring is, maar welke redenen voor uitstel in de betreffende situaties aantoonbaar zijn. Ook andere verklaringen en gevallen waarin uitstroom wel lukt moeten worden meegenomen."] },
        { id: "bronnen-en-methode", title: "Welke bronnen zijn nodig?", paragraphs: ["Voor de reconstructie zijn gedateerde besluiten, beschrijvingen van verantwoordelijkheden en gegevens over instroom en uitstroom nodig. Bij iedere meting moeten definitie, periode, populatie en herkomst zichtbaar zijn. Een algemeen cijfer is niet automatisch toepasbaar op een individuele situatie.", "Ervaringen kunnen onderzoeksvragen zichtbaar maken, maar tellen niet vanzelf als bewijs voor een landelijk patroon. Documenten en interviews moeten op hun eigen betekenis worden beoordeeld. Persoonsgegevens worden niet automatisch openbaar gemaakt."] },
        { id: "alternatieve-verklaringen", title: "Wat kan de eerste verklaring tegenspreken?", paragraphs: ["Een voorgesteld verband tussen wonen en zorg is een hypothese. Het dossier moet laten zien welke informatie die hypothese kan ondersteunen, beperken of weerleggen. Verschillen tussen regio’s, voorzieningen en groepen mogen niet ongemerkt in één conclusie worden samengevoegd.", "Het ontbreken van een document is geen bewijs dat een organisatie informatie bewust heeft achtergehouden. Ontbrekende informatie wordt een concrete vervolgvraag, met vermelding van wat nodig is om die vraag te beantwoorden."] },
        { id: "van-onderzoek-naar-keuze", title: "Waar begint de politieke keuze?", paragraphs: ["Meridian beschrijft de onderzoeksvraag, methode en later de onderbouwde bevindingen. Ampara kan daaraan een politieke afweging verbinden. Die afweging moet herkenbaar blijven als keuze en mag niet met terugwerkende kracht bepalen wat het onderzoek concludeert.", "Een voorstel is pas beoordeelbaar wanneer duidelijk is welk probleem het adresseert, op welke bronnen het rust, wie het kan uitvoeren en hoe de uitkomst wordt gecontroleerd. In deze onderzoeksopzet is nog geen vastgesteld voorstel opgenomen."] }
    ]
};
