import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';import {JSDOM} from 'jsdom';
const dom=new JSDOM('<div id="root"></div><div class="admin-editor-grid"><form id="legacy"><input name="title" value="Bewaar tekst"><select name="section_type"><option value="paragraph" selected>Alinea</option><option value="quote">Quote</option></select></form></div>',{url:'https://meridian.test/admin/content/test'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,Element:dom.window.Element,HTMLElement:dom.window.HTMLElement,HTMLInputElement:dom.window.HTMLInputElement,IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});window.confirm=()=>true;
dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
const React=await import('react'),{createRoot}=await import('react-dom/client'),{renderToStaticMarkup}=await import('react-dom/server'),{act}=React,require=createRequire(import.meta.url);
const id='10000000-0000-4000-8000-000000000001';let config,version,calls,finishUpload,uploadFails=false;
const site={selected:true,slug:'eerste',indexable:true,featured:false,position:'side',canonical:'self',description:'Eigen SEO',seo_title:'Mijn titel'};
function reset(){version=1;calls=[];uploadFails=false;config={tags:['behouden'],relations:[],sites:{meridian:{...site},avera:{...site,selected:false}},hero_image:'https://images.test/oud.jpg',image_alt:'Oude foto'};document.getElementById('legacy').reset();}
const actions={loadPublishingContext:async()=>({ok:true,value:{version,config:structuredClone(config),sites:[{id:'meridian',label:'Meridian',origin:'https://meridiancollective.nl'},{id:'avera',label:'Amparis',origin:'https://www.amparis.nl'}],reports:[],editions:[]}}),savePublishingConfig:async(_id,v,c)=>{calls.push(['save',v,structuredClone(c)]);config=structuredClone(c);return {ok:true,value:++version};},publishSharedArticle:async value=>{calls.push(['publish',value]);return {ok:true,value:{revision_id:'released'}};}};
const storage={upload:async(_path,_blob,options)=>{calls.push(['upload',options]);await new Promise(resolve=>{finishUpload=resolve;});return {error:uploadFails?{message:'failed'}:null};},getPublicUrl:()=>({data:{publicUrl:'https://storage.test/vervangen.jpg'}})};
function load(file,mocks={},cache=new Map()){
 file=path.resolve(file);if(cache.has(file))return cache.get(file);if(file.endsWith('.json'))return JSON.parse(fs.readFileSync(file,'utf8'));
 const mod={exports:{}},source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true,resolveJsonModule:true}}).outputText;
 function local(name){if(Object.hasOwn(mocks,name))return mocks[name];if(name==='server-only'||name.endsWith('.css'))return {};if(name==='next/link')return ({children,...props})=>React.createElement('a',props,children);
 if(name==='@/app/admin/publishing-actions')return actions;if(name==='@/app/admin/content/workspace-actions')return {loadWritingDocument:async()=>({ok:true,value:{revision:'saved-text'}})};
 if(name==='@/lib/supabase/client')return {createClient:()=>({auth:{getUser:async()=>({data:{user:{id}},error:null})},storage:{from:()=>storage}})};
 if(name==='@/lib/admin/article-image')return {ARTICLE_IMAGE_BUCKET:'article-images',prepareArticleImage:async()=>({blob:new Blob(['jpeg']),format:{mime:'image/jpeg',extension:'jpg'}})};
 if(name.startsWith('.')||name.startsWith('@/')){const base=name.startsWith('@/')?path.resolve('src',name.slice(2)):path.resolve(path.dirname(file),name);return load([base,base+'.ts',base+'.tsx',base+'.json'].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile()),mocks,cache);}return require(name);}
 new Function('require','module','exports',source)(local,mod,mod.exports);cache.set(file,mod.exports);return mod.exports;
}
const Quick=load('src/components/admin/publishing/QuickPublish.tsx').default,helper=load('src/lib/admin/unsaved-publication-form.ts'),root=createRoot(document.getElementById('root'));
after(async()=>{await act(async()=>root.unmount());dom.window.close();});
const button=text=>{const b=[...document.querySelectorAll('#root button')].find(b=>b.textContent.trim()===text);assert.ok(b,text);return b;};
const click=b=>act(async()=>b.click());
async function mount(){await act(async()=>root.render(null));reset();await act(async()=>root.render(React.createElement(Quick,{id,revision:'saved-text',dirty:false,inline:true,refreshRevisionOnOpen:true})));}
async function normal(){const select=document.querySelector('.article-display-options select');await act(async()=>{select.value='normal';select.dispatchEvent(new window.Event('change',{bubbles:true}));});}
async function upload(){const input=document.querySelector('input[type="file"]');Object.defineProperty(input,'files',{value:[new File(['jpeg'],'foto.JPEG',{type:'image/jpeg'})],configurable:true});await act(async()=>input.dispatchEvent(new window.Event('change',{bubbles:true})));}

test('inline editor has a visible JPEG chooser and per-site normal article option without opening a dialog',async()=>{await mount();assert.equal(document.querySelector('dialog'),null);assert.match(document.querySelector('#root h2').textContent,/Afbeelding en artikelweergave/);assert.match(document.querySelector('input[type="file"]').accept,/\.jpeg/);assert.equal(document.querySelectorAll('.article-display-options select').length,2);});
test('JPEG replaces the preview only on success and publishes the chosen display with saved text',async()=>{await mount();await upload();assert.equal(button('Publiceer op Meridian').disabled,true);assert.equal(document.querySelector('.article-image-preview img').src,'https://images.test/oud.jpg');await act(async()=>finishUpload());assert.equal(document.querySelector('.article-image-preview img').src,'https://storage.test/vervangen.jpg');await normal();await click(button('Publiceer op Meridian'));assert.deepEqual(calls.map(c=>c[0]),['upload','save','publish']);assert.equal(calls[0][1].upsert,false);assert.equal(calls[1][2].hero_image,'https://storage.test/vervangen.jpg');assert.equal(calls[1][2].sites.meridian.show_chapters,false);assert.equal(calls[1][2].sites.avera.show_chapters,undefined);assert.equal(calls[2][1].revision,'saved-text');assert.deepEqual(config.tags,['behouden']);assert.equal(config.sites.meridian.description,'Eigen SEO');});
test('failed JPEG upload preserves the previous image and does not save or publish',async()=>{await mount();uploadFails=true;await upload();await act(async()=>finishUpload());assert.equal(document.querySelector('.article-image-preview img').src,'https://images.test/oud.jpg');assert.match(document.querySelector('.article-image-error').textContent,/niet gelukt/);assert.deepEqual(calls.map(c=>c[0]),['upload']);});
test('draft display save never publishes and unsaved image/display prevents losing it to a text-form submit',async()=>{await mount();await normal();let allowed;await act(async()=>{allowed=document.getElementById('legacy').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));});assert.equal(allowed,false);await click(button('Als concept opslaan'));assert.deepEqual(calls.map(c=>c[0]),['save']);assert.equal(config.sites.meridian.show_chapters,false);});
test('changing a text block type is detected and blocks publication until the form is saved',async()=>{await mount();document.querySelector('#legacy select').value='quote';assert.equal(helper.hasUnsavedPublicationForm(document),true);await click(button('Publiceer op Meridian'));assert.deepEqual(calls,[]);assert.match(document.querySelector('[role="alert"]').textContent,/tekstformulier/);document.getElementById('legacy').reset();assert.equal(helper.hasUnsavedPublicationForm(document),false);});
test('normal public rendering keeps article body and headings without report navigation or report SEO',()=>{const View=load('src/components/publishing/SharedArticleView.tsx').default;const article={id,slug:'eerste',content_type:'article',title:'Eerste artikel',summary:'Samenvatting',subtitle:null,eyebrow:null,hero_image:null,image_alt:null,status:'published',platform:'meridian',origin:'https://meridiancollective.nl',canonical_url:null,published_at:'2026-09-21T12:00:00Z',updated_at:'2026-09-21T12:00:00Z',seo:{...site,show_chapters:false},targets:{},report:null,content_sections:[{id:'a',position:0,section_type:'paragraph',title:'Tussenkop',body:'Tekst behouden.',data:{}}]};const html=renderToStaticMarkup(React.createElement(View,{article}));assert.match(html,/Tussenkop/);assert.match(html,/Tekst behouden/);assert.doesNotMatch(html,/pub-chapter-nav|CreativeWorkSeries|\/verslagen\//);});
