import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url);
function load(file){const output={exports:{}};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const localRequire=name=>name.startsWith('.')?load(path.resolve(path.dirname(file),name+'.ts')):require(name);new Function('require','module','exports',code)(localRequire,output,output.exports);return output.exports;}
const model=load(path.resolve('src/lib/publishing/model.ts')),seo=load(path.resolve('src/lib/publishing/seo.ts'));
const id='10000000-0000-4000-8000-000000000001',section='30000000-0000-4000-8000-000000000001';
test('inline links preserve visible words and use stable article/section identities',()=>{const token=model.contentLink('Meer lezen',id,section);const targets={[id]:{href:'/artikelen/ander-adres',title:'Titel',sections:[section]}};assert.deepEqual(model.inlineParts(`Begin ${token}.`,targets),[{text:'Begin ',href:null},{text:'Meer lezen',href:`/artikelen/ander-adres#section-${section}`},{text:'.',href:null}]);assert.equal(model.plainText(token),'Meer lezen');assert.equal(model.inlineParts(token)[0].href,null);assert.equal(model.resolveContentHref(`content:${id}#section-${section}`,{[id]:{...targets[id],sections:[]}}),'/artikelen/ander-adres');});
test('unsafe URL schemes and HTML stay inert; JSON-LD cannot close its script',()=>{for(const url of ['javascript:alert(1)','//evil.test','/\\evil.test','data:text/html,test','https://a:b@evil.test'])assert.equal(model.safeHref(url),null);const parts=model.inlineParts('[x](javascript:alert(1)) <script>alert(1)</script>');assert.ok(parts.every(p=>p.href===null));assert.doesNotMatch(model.jsonLdString({text:'</script><script>alert(1)</script>'}),/</);});
test('chapter navigation uses the visible order, not arithmetic or a link to chapter one',()=>{const r={chapters:[{id:'a'},{id:'b'},{id:'d'}]};assert.equal(model.chapterNeighbours(r,'b').next.id,'d');assert.equal(model.chapterNeighbours(r,'a').previous,null);assert.equal(model.chapterNeighbours(r,'missing').next,null);});
test('metadata is chapter-specific, applies indexability and uses the selected canonical',()=>{const article={slug:'hoofdstuk-twee',title:'Tweede hoofdstuk',summary:'Samenvatting',origin:'https://meridian.test',canonical_url:'https://meridian.test/artikelen/hoofdstuk-twee',seo:{indexable:true},published_at:'2026-09-18T00:00:00Z',updated_at:'2026-09-18T00:00:00Z',platform:'meridian',report:{slug:'verslag',title:'Verslag'}};const meta=seo.articleMetadata(article);assert.equal(meta.alternates.canonical,article.canonical_url);assert.equal(meta.title,article.title);assert.equal(seo.articleMetadata({...article,seo:{indexable:false}}).robots.index,false);assert.equal(seo.articleStructuredData(article).isPartOf.url,'https://meridian.test/verslagen/verslag');});
