// Temporary UI fixture. Removed before merging the design into main.
import Link from "next/link";
import AuthLayout from "@/app/(auth)/layout";
import AuthForm from "@/components/account/AuthForm";
import WorkspaceShell from "@/components/account/WorkspaceShell";
import LibraryCards from "@/components/account/LibraryCards";
import MemberEditor from "@/components/account/MemberEditor";
export const metadata = { robots: { index: false, follow: false } };
export default async function Review({searchParams}: {searchParams:Promise<{view?:string;frame?:string}>}) {
 const {view,frame}=await searchParams;
 if(frame) return <main style={{margin:0,background:"#f3f4f6",padding:20}}><p>Mobiele ontwerpcontrole — voorbeeldgegevens</p><iframe title="Mobiele ontwerpcontrole" src={`/account-preview?view=${encodeURIComponent(view??"library")}`} width="390" height="844" style={{border:"1px solid #ccc"}}/></main>;
 if(view === "register") return <AuthLayout><AuthForm mode="register"/></AuthLayout>;
 const items = [{href:"/account-preview",label:"Overzicht",icon:"overview" as const},{href:"/account-preview?view=library",label:"Bibliotheek",icon:"library" as const},{href:"/account/opgeslagen",label:"Opgeslagen",icon:"bookmark" as const},{href:"/account/profiel",label:"Profiel & privacy",icon:"profile" as const}];
 if(view === "editor") return <WorkspaceShell mode="admin" items={[{href:"/account-preview",label:"Ledenpublicaties",icon:"write"},{href:"/admin/gebruikers",label:"Gebruikers",icon:"users"}]}><div className="member-admin"><div className="workspace-page-heading"><div><p className="member-eyebrow">Ontwerpcontrole · voorbeeld</p><h1>Nieuwe ledenpublicatie</h1></div></div><MemberEditor members={[{id:"00000000-0000-0000-0000-000000000001",display_name:"Voorbeeldlezer",email:"lezer@example.invalid",created_at:"2026-01-01",total_count:1}]}/></div></WorkspaceShell>;
 return <WorkspaceShell items={items}><div className="member-container"><div className="workspace-page-heading"><div><h1>Jouw overzicht</h1><p>Ontwerpcontrole met voorbeeldpublicaties.</p></div><Link className="member-button" href="/account-preview?view=register">Open bibliotheek →</Link></div><div className="workspace-stats">{[["6","In je bibliotheek"],["2","Persoonlijk gedeeld"],["3","Opgeslagen"]].map(([n,label])=><div key={label}><span><strong>{n}</strong><small>{label}</small></span></div>)}</div><div className="workspace-columns"><section className="workspace-panel"><header className="workspace-panel-header"><h2>Laatst toegevoegd</h2><Link href="/account-preview?view=editor">Bekijk alles →</Link></header><LibraryCards items={["Hoe alles met elkaar samenhangt","Een ander perspectief op verandering","De wereld achter het nieuws","Speciaal voor jou: verder lezen","Wat een systeem zichtbaar maakt","Een persoonlijke leesroute"].map((title,i)=>({id:String(i),slug:"voorbeeld",title,summary:"Een korte introductie bij deze voorbeeldpublicatie om de nieuwe indeling te beoordelen.",kind:i%2?"text":"article",audience:i%3?"members":"selected"}))}/></section><aside className="workspace-context"><p className="member-eyebrow">Jouw account</p><h2>Snel verder</h2>{["Persoonlijk voor jou","Je leeslijst","Profiel & privacy"].map(label=><Link key={label} href="/account-preview?view=editor" className="workspace-context-link"><strong>{label}</strong><span>→</span></Link>)}</aside></div></div></WorkspaceShell>;
}
